### ISSUE TITLE
save as?

### ISSUE THREAD

**Issue by jccalhoun** [paulgb/Treeverse#1]
Treeverse has become quite useful in my research. Is there a way to do a "save as" with the treeverse.html page so the user can pick the name it is saved under?

**Comment by paulgb** [comment]
Thanks for the suggestion. I've added a prompt allowing you to rename the file, does that fulfill your need?

(It's still in the app store publishing phase but it should update automatically in your browser within an hour or so.)

**Comment by jccalhoun** [comment]
This is great. Thanks!

Would it be possible to pick a location to save it to as well? I can move it to my preferred directory after it is saved but it would be nice if I could pick it right away.

**Comment by paulgb** [comment]
Unfortunately it's not possible for a chrome extension to save files anywhere but the download directory for security reasons. It might be possible to create a link that you could right-click and save as... I'll leave this ticket open until I think a bit more about what the best approach is.

**Comment by aborruso** [comment]
Hi @jccalhoun how to view saved Treeverse.html file?

Thank you
