### ISSUE TITLE
Error MSG: No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by Bortseb** [paulgb/Treeverse#11]
The extension isn't working for me, here is what is in my console:

`XMLHttpRequest cannot load https://twitter.com/Bortseb/status/897884889458106369. Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'chrome-extension://aahmjdadniahaicebomlagekkcnlcila' is therefore not allowed access. The response had HTTP status code 400.`

**Comment by paulgb** [comment]
Thanks, I'll take a look

**Comment by paulgb** [comment]
I can't actually replicate the issue, but I've added a permission that I think might fix it. It will take an hour or so to update in the app store but after that let me know if it works for you.

**Comment by Bortseb** [comment]
Works now!

**Comment by paulgb** [comment]
Great! Thanks for reporting.
