### ISSUE TITLE
making it easier to read the whole tree

### ISSUE THREAD

**Issue by jeisner** [paulgb/Treeverse#12]
Thanks very much for Treeverse!
Often I want to read a whole discussion there, but it's hard to keep track of where I've been.
Would you be interested in some UI ideas for this?

One idea involves allowing the user to mark nodes that they've already read.
Another involves keyboard navigation [I realize there's some already].
These ideas could be combined.  
Details on request! :sweat_smile:

**Comment by paulgb** [comment]
Hi Jason,

I don't have a lot of time to spend on Treeverse these days but if you end
up implementing anything feel free to send a PR and I'll look it over.
