### ISSUE TITLE
Treeverse seems not work anymore

### ISSUE THREAD

**Issue by ISMResearcher** [paulgb/Treeverse#14]
Once you click on the treeverse chrome add on - it opens the new tab...with the blank window but it does not load any tweet data. Not sure if it is a Twitter issue or if somehow Treeverse has stopped working.

**Comment by paulgb** [comment]
I just published a new version that seems to fix the issue. It will auto-update for you, you will know that it has updated when the visualization description text changes to this:

<img width="485" alt="screen shot 2018-04-24 at 7 58 26 pm" src="https://user-images.githubusercontent.com/46173/39219658-e36342dc-47f9-11e8-94a5-1f3cca9b53d6.png">

If it still doesn't work for you once it has updated, please let me know!
