### ISSUE TITLE
How could I turn Treeverse into a command line tool to get conversation trees?

### ISSUE THREAD

**Issue by jeromecc** [paulgb/Treeverse#18]
Hi!
Thanks for Treeverse.
Contrary to "twarc replies --recursive", Treeverse is able to retrieve conversations older than the search limit (which is 7 or 30 days).
I would like to add the possibility to retrieve conversations (status_id as a tree structure, or just status_id & in_reply_to_status_id pairs or in twarc json format) automatically while using Treeverse as a script or a command inside a terminal.
I am new to TypeScript (I know C++, Python and a bit of JavaScript). Do you think it can be done? Would it be easier to just use the brute-force method "list all reply to a given username, filter by in_reply_to_status_id) in a Python script (which is not so easy because tools like TweetScraper don't retrieve "in_reply_to_status_id" so I'd have to make speed limiting API calls)?
Do you have suggestions or recommendations on how to achieve this? I wouldn't want to start hacking in the wrong direction... :-)
Thanks.

**Comment by paulgb** [comment]
Treeverse works by requesting the actual HTML content from Twitter, which (as a former API developer who got burned by Twitter) I actually find more stable than the "official" APIs.

The meat of the code that fetches and parses this content is in `tweet_server.ts` and `tweet_parser.ts`, respectively. The idea is that you'd call something like `TweetServer.fetchTweets({username: 'blah', id: 124343242});` which would give you a TweetContext object that has `ancestors` and `descendants` properties where ancestors is a list of tweets and descendants is a list of chains of tweets. If you wanted the whole tree you could recursively call `fetchTweets` again on those tweets.

It *should* be possible to get it running from the command line through node.js, but I'd be surprised if it worked out of the box without some tweaking of the HTTP requests to Twitter. They are pretty picky about what requests they accept -- one of the reasons that it's nice that it runs in the browser is that this is all done for you (e.g. the authorization cookies are sent, so the requests are made as the logged-in user.)

Hope that helps
-- Paul
