### ISSUE TITLE
Fix stuff that broke in the most recent Twitter change

### ISSUE THREAD

**Issue by paulgb** [paulgb/Treeverse#19]
A recent Twitter change resulted in a big change in how Treeverse works. Instead of opening up a new tab, Treeverse injects itself into the current HTML page.

These things are known to be broken:
- The download button has been removed for now because the way offline export worked made some assumptions about the page that have changed.
- ~~Loading "deeper" works, but loading "broader" does not.~~ (fixed in 1.3)
- Warnings appear in the console from Semantic UI over font loading.
- ~~It breaks the back button.~~ (fixed in 2.0)
- Archive mode doesn't work (#21)

**Comment by ISMResearcher** [comment]
Thanks Paul for fixing this - do you think it will be fully operational again? or is Twitter changes a permanent problem?

**Comment by paulgb** [comment]
I think I can return to feature parity with what worked before. I was traveling for most of August so I haven't had a chance to sit down and tackle it yet.

**Comment by paulgb** [comment]
Published version 1.3 in the app store which *should* bring the tweet exploring UI back to parity with what it was before. Some additional features remain broken.

**Comment by ISMResearcher** [comment]
Thanks - super interested in exploring responses to the new Nike Kaepernick
campaign :) I think there will be some interesting discussion threads
there.


Dr. Ann Pegoraro
Full Professor
Laurentian University
705-675-1151 ext. 1011
@sportmgmtprof <http://www.spad.ca>
www.sportmarketing.ca

**Comment by ISMResearcher** [comment]
Encountering some issues with loader broader this morning...could just be me, but not sure.

**Comment by paulgb** [comment]
Thanks for reporting. I'll have a better look at this over the weekend, but
in the meantime is it happening for all tweets or just some? If just some
could you send an example?

Cheers

**Comment by paulgb** [comment]
2.0 released
