### ISSUE TITLE
Super-long posts (as with long URLs or large images) can't scroll

### ISSUE THREAD

**Issue by infinitebuffalo** [paulgb/Treeverse#22]
Long posts that are too tall for the window don't seem to get a scroll bar, and seemingly can only occasionally be scrolled with the mouse wheel, either.

See, for an example, the right-side reply to this post: https://twitter.com/bikelaneuprise/status/1037351778860318725  
![treeverse_toobig2](https://user-images.githubusercontent.com/7200103/46227779-36cb3880-c32e-11e8-9aa3-9fa50d96fdfc.PNG)

I have unfortunately lost the source on this one, but the issue is similar — a photo attached to the tweet is so tall that it pushes up under the infobox, and with no ability to scroll, it's impossible to see all the text.  
![treeverse_toobig](https://user-images.githubusercontent.com/7200103/46227861-68dc9a80-c32e-11e8-83ae-5039f1aef12e.PNG)

Here's another image example, from https://twitter.com/bikelaneuprise/status/1037026430440361984. This one for some reason I _was_ able to scroll with the mouse wheel.  
![treeverse_toobig3](https://user-images.githubusercontent.com/7200103/46228886-8e1ed800-c331-11e8-820a-d4a8c4cc3280.png)

**Comment by paulgb** [comment]
Thanks for reporting. There are two separate bugs here, so I've opened an issue to track both of them and will close this issue. The bugs are:
- The fact that the infobox can obscure content (#23)
- The fact that long URLs are not condensed (#24)

Cheers,

-- Paul
