### ISSUE TITLE
`nextChildren` in `tweet_parser.ts` is unnecessary 

### ISSUE THREAD

**Issue by jeromecc** [paulgb/Treeverse#30]
Hi!
I have a question about the parser.

On line 149 of src/viewer/tweet_parser.ts
    
    let nextChildren = [];

What is the purpose of the array nextChildren that is not returned or used inside the function? Future purpose? Idea in progress? Leftover? I might also have missed something.

Thanks for your work which I am trying to adapt for Python in order to retrieve the tree structure of conversations.

**Comment by paulgb** [comment]
Hi Jerome, you are right that it does not do anything. It appears I added it in this commit: 

https://github.com/paulgb/Treeverse/commit/2416a4c2fba8483678324dba2e62787bfbc48654

It dates back to when I was still figuring out how the Twitter web client talks to the server so it must have been something I tried and removed but didn't remove cleanly. I will remove it and use this issue to track it.
