### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by WestonThayer** [paulgb/Treeverse#37]
Version: 3.1

The page seems to refresh when clicking the extension, but it doesn't display. No console errors. I ran it incognito so as to assure there were no other extensions that could interfere.

![untitled](https://user-images.githubusercontent.com/709153/52597091-d2090a00-2e06-11e9-9d15-3f45412cae46.gif)

**Comment by paulgb** [comment]
Hi,

Thanks for reporting this. I think with Twitter's new UI change, the API
treeverse hits is only available for logged-in users.

I'm sorry for the bad UI if that's the case. I'd like to at least improve
that if it isn't possible to fix treeverse in logged-out cases.

Notes for my own use:

Currently, if Treeverse has not yet captured the auth tokens it needs, it
refreshes the page expecting to get them, and then launches into the
Treeverse view. But they are not sent if you are logged out so it never
gets them, and so it never triggers the Treeverse view.

I'll use this issue to track:
- [ ] displaying an error message when the UI can't load (after a timeout)
- [ ] figuring out if there's still a way to support logged-out users

**Comment by paulgb** [comment]
I'll use this issue to track:
- [ ] displaying an error message when the UI can't load (after a timeout)
- [ ] figuring out if there's still a way to support logged-out users

**Comment by WestonThayer** [comment]
Thanks for the quick response! I'm seeing the same issue while logged in unfortunately. Again, no console logs, just the page refresh.

![untitled](https://user-images.githubusercontent.com/709153/52601032-6b89e900-2e12-11e9-8c4b-c53a94da486a.gif)

P.S. thank you for this extension, it's a lifesaver for big threads.

**Comment by WestonThayer** [comment]
Trying to help debug here; going off [this line](https://github.com/paulgb/Treeverse/blob/24e5c9509be7ae645b0f5a2b6be5cf9628aa993d/src/background/chrome_action.ts#L7), I'm not seeing any network requests to `api.twitter.com` when refreshing the page:

![image](https://user-images.githubusercontent.com/709153/52601321-33cf7100-2e13-11e9-9d56-18f25b49f5c9.png)

I wonder if I'm on an A/B test where their web app isn't making those calls anymore?

**Comment by WestonThayer** [comment]
Vanilla install, just to rule out any user settings: [image](https://user-images.githubusercontent.com/709153/52601707-8d846b00-2e14-11e9-85ac-6c201915c51f.png)

**Comment by paulgb** [comment]
Thanks for the additional info.

It looks like Twitter reverted some people (including me) *back* to the old UI (!?)

Do you have this option?

<img width="223" alt="screen shot 2019-02-11 at 7 37 55 pm" src="https://user-images.githubusercontent.com/46173/52603473-f4198100-2e34-11e9-9661-729e89238f7f.png">

**Comment by WestonThayer** [comment]
Nope, dang. Doesn't look like there's an easy way to downgrade Chrome extensions either. Oh well, I can wait 😕

**Comment by paulgb** [comment]
Hmm, that’s odd, the option doesn’t appear at all?

I am not sure what’s going on with this on Twitter’s end, I waited until I thought it was a 100% roll-out of the new UI but it seems like they’re actually rolling it back(?). I wonder if they ran into some issues with it and are walking it back temporarily.

If you’re willing to build from source, you could get the most recent version made to work with the old UI from this commit: https://github.com/paulgb/Treeverse/tree/b0b87ae5ba1bd4a64d4ae8f788662ecbaf0477ad

To build, you’ll need `npm` or `yarn`. Run `npm install` or `yarn install`, then `./build_extensions.sh`. The resulting `extension_chrome.zip` file will be version 2.5 of the extension.

**Comment by paulgb** [comment]
I know it’s not much help to you at this point, but I just published v 3.2 to the Chrome app store which adds a message when it can’t load Twitter.

**Comment by WestonThayer** [comment]
No, I don’t get that option in my account drop down. I’ll bet you’re right, they’re having issues. 

Thanks for the error message, I’ll try the old sources when I get a chance.

**Comment by ISMResearcher** [comment]
Treeverse was working for me - now I get a Message "you are either logged out of Twitter or using old Twitter UI" but I don't have an option to try new twitter. So I will just wait

**Comment by infinitebuffalo** [comment]
So, I was also at some point—probably around the time of @ISMResearcher's comment, though I don't recall—getting a message from Treeverse about being logged out or using old Twitter.  Now that it's mid-April, I have no idea if I'm on new-Twitter or not (I don't have any menu options about reverting or going forward), but I do know Treeverse is not working.

I recently discovered there's a Firefox version and installed that, and I get the behaviour @WestonThayer describes where the twitter page simply refreshes.  In Chrome, the button doesn't even light up, so when I click on it I just get the standard Chrome extension-button menu.

**Comment by paulgb** [comment]
Sorry for the inconvenience. Twitter made some changes that apply to some
users but not others and it's been a pain to make Treeverse work for both
groups of users :( I was sure that they would have moved everyone over to
the same interface by now but they have not.

I have an idea though, would you mind going to mobile.twitter.com and
taking a screenshot of the header bar? I'm thinking that even if the
Twitter.com interface is not consistent the mobile interface may be.

**Comment by infinitebuffalo** [comment]
header bar:
![Capture](https://user-images.githubusercontent.com/7200103/56372733-8d666a00-61cd-11e9-8d7f-75f65093e9e9.PNG)

(FWIW, the Chrome extension apparently does not activate for mobile.twitter, either, though in Firefox it does seem to function.)

**Comment by paulgb** [comment]
Oh, that’s the new UI! This is good news, I have a theory that Twitter has
made the new UI available for everyone as mobile.twitter.com, in which case
I can simply redirect everyone there. I’ll give it a try.

**Comment by alexey-zaharchenko** [comment]
Any news?

**Comment by drandreaskrueger** [comment]
> Not working anymore.

Is it working again?

I got it partially working on the root tweet of a tree, but then

(a) I could not expand most children comments, and   

(b) when I _start_ Treeverse at a child tweet (i.e. a comment), it only shows one rounded square with the avatar of the author, but nothing else. And it cannot be expanded. Double clicking the author avatar starts a web request, but nothing changes in the picture, and the CTRL-Shift-J console shows no errors.

Tried both in Firefox v67 and Chrome v75, and yes, I was logged in.

How to debug?

**Comment by WestonThayer** [comment]
FWIW I *finally* got the new Twitter and now it works great! I can repro @drandreaskrueger's second issue (b) above, but it's no trouble to go to the root Tweet. Haven't hit (a) yet.

**Comment by drandreaskrueger** [comment]
The tweet I am interested in is one level below the root tweet.  
And it is just not expanding. regardless whether I start with that tweet or its parent, the root tweet.

**Comment by paulgb** [comment]
@drandreaskrueger can you send me a tweet that has this issue so I can see if I can reproduce it?

Now that the new Twitter UI is launched to everyone I should be able to make this more stable, thanks for your patience.

**Comment by drandreaskrueger** [comment]
Thanks, @paulgb - looks like it's solved now: https://github.com/paulgb/Treeverse/issues/40#issuecomment-513409667
