### ISSUE TITLE
Cannot expand "show more replies"

### ISSUE THREAD

**Issue by PierrotLL** [paulgb/Treeverse#40]
Hi,
It seems like Treeverse can't load tweets hidden behind the "show more replies" link.
In this case, there is an ellipsis on the tweet, and the double-click just makes it disappear, without any branch appears.
It only happens with tweets displayed with "show more replies" below in twitter display.

Thanks a lot for this app, Treeverse is amazing :)

**Comment by paulgb** [comment]
Thanks for reporting, sorry about that. I’m working on a rewrite that should fix this and some of the stability issues.

**Comment by drandreaskrueger** [comment]
Might that be related to this issue too?

https://github.com/paulgb/Treeverse/issues/37#issuecomment-511619155

**Comment by drandreaskrueger** [comment]
and: sorry for the selfish question, but for a quick fix of my current task: Which alternative software exists, to visualize the tree structure of a branched discussion? Thanks.

**Comment by paulgb** [comment]
@drandreaskrueger the [twarc-report](https://github.com/pbinkley/twarc-report) project may interest you.

**Comment by paulgb** [comment]
I have released version 3.3 of Treeverse which should fix this issue, let me know if you still have problems.

**Comment by PierrotLL** [comment]
Fix confirmed, it works !
Thank you very much :)

**Comment by paulgb** [comment]
Thanks for confirming!

**Comment by drandreaskrueger** [comment]
Hooray, you did it. It's working now! Thank you so much. 

Very very useful tool.  
It's actually pretty easy to loose the overview of a branching discussion.
And this then helps a lot.
