### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by aborruso** [paulgb/Treeverse#43]
Hi,
when I use it with the latest google chrome in Win 10, I have

![image](https://user-images.githubusercontent.com/30607/61547202-32057b80-aa4b-11e9-89c8-69e4ecedfc0b.png)

**Comment by paulgb** [comment]
Thanks for reporting this. A few questions that may help me get to the
bottom of this:

- Are you logged in to Twitter? (I should modify the message to clarify
that that is necessary, or at least test if it is still necessary now that
even logged-out users get the new UI)
- Have you tried refreshing the Twitter page and seeing if you still get it?
- One thing that makes it hard to get this right is that Twitter seems to
serve different stuff to different regions -- are you in Italy?

Regards,

-- Paul

**Comment by aborruso** [comment]
Hi,

On Fri, 19 Jul 2019 at 17:39, Paul Butler <notifications@github.com> wrote:

>
> - Are you logged in to Twitter? (I should modify the message to clarify
> that that is necessary, or at least test if it is still necessary now that
> even logged-out users get the new UI)
>

yes, I'm logged.


> - Have you tried refreshing the Twitter page and seeing if you still get
> it?
>

Yes, it's the same


> - One thing that makes it hard to get this right is that Twitter seems to
> serve different stuff to different regions -- are you in Italy?
>

I'm in Italy

Thank you

**Comment by rchikhi** [comment]
Happens in France too
