### ISSUE TITLE
rate-limited?

### ISSUE THREAD

**Issue by drandreaskrueger** [paulgb/Treeverse#44]
The tree stopped expanding.

And it took me a while to realize I can open the console.  

There I saw hundreds of such pink errors:
   
![treeverse-errors_anon](https://user-images.githubusercontent.com/7796035/61841495-42778500-ae95-11e9-827a-55038270d90e.png)

... only then I realized that perhaps I got rate-limited? It was a large tree.

### What would be mitigation methods?  Some ideas:

* show in the GUI when that error happens
  * only much later I realized that pressing "stop expanding" was the right thing to do
* auto-stop the expanding after 5 such messages came in?
* additional option to fill in some (0.01s ? 0.1s, 0.5s, 1s ?) delay between each API call, to escape from ANY rate-limiting by twitter?

Now that I know what can happen, I will find my way around, I guess. For newbs though, a solution could be fruitful.

Thanks for this amazing tool. Have used it for the second discussion now. Great!

**Comment by paulgb** [comment]
Thanks for reporting, I’ll look into, at minimum, recognizing when we hit a rate limit error. It’s also a prerequisite for #20. 

It’s also embarrassing that those `h1` and `h2` log statements made it into production -- will have to fix that.

**Comment by drandreaskrueger** [comment]
Yes, I had a smile on my face when I discovered it, but not embarassing, no.

Actually, they had a VERY useful side effect: I could see whenever an API call came back. 
So: Don't just remove it, without finding another way of providing that feedback. And if only a console.log("."). Or an incrementing counter? Something blinking in the GUI?

**Comment by paulgb** [comment]
Good point. Come to think of it, it would be useful to use the console to
log real debugging messages (x replies loaded, etc.)

I don't see the harm in adding that.

**Comment by paulgb** [comment]
Opened #49 to track console logging.
