### ISSUE TITLE
Get ancestors of tweets in threads (crawling upwards)?

### ISSUE THREAD

**Issue by ronentk** [paulgb/treeverse#57]
Sorry if maybe this isn't possible in Twitter, it would make this app really useful to me (already use it a lot!).

I saw #45 discussed downward traversal options, is there anything preventing traversing threads up to the source from which all replies were issued?

**Comment by paulgb** [comment]
Unfortunately, not currently. I'll leave this open as a feature request.

**Comment by nandana** [comment]
Yes, +1. It would be quite useful.
