### ISSUE TITLE
Treeverse isn't working on Chrome.

### ISSUE THREAD

**Issue by paulgb** [paulgb/Treeverse#60]
As reported here: https://twitter.com/PKolachina/status/1258813454590361600

Able to replicate on Mac with Version 81.0.4044.129 (Official Build) (64-bit)

FireFox version still appears to work, indicating this is more likely a change in a Chrome API than a Twitter API.

**Comment by houshuang** [comment]
Noticed this, and it's very sad. I thought it was a change to the Twitter API/DOM, but if it's still working on other browsers, I can try digging into the code - any ideas where I should start looking?

**Comment by paulgb** [comment]
It looks like the callback set by [this line](https://github.com/paulgb/Treeverse/blob/0fed4984133a6dfbc9f6295ec424b57c34afc7c1/src/background/chrome_action.ts#L5) is no longer called by the browser.

I suspect that either:
- A chrome change locked down the ability of extensions to add header listeners.
- A Twitter change started using a new web security feature that I'm not familiar with to lock down the extension's ability to add the listener.

In either case, it's weird that there is no error message when the listener is installed. Any digging on figuring out why it's not invoked would be helpful!

**Comment by paulgb** [comment]
Well, I have some bad news. It looks like since Chrome 79 (December 2019), the headers sent by `onBeforeSendHeaders` are extremely limited. Although the documentation doesn't say so, it appears the same restrictions apply to `onSendHeaders`.

![image](https://user-images.githubusercontent.com/46173/82844764-b9175180-9eaf-11ea-8af6-1b967176fe9f.png)

What's weird is *sometimes* it still works for me, so maybe there's hope in that if the request is triggered in the right way we still get the headers we need (in both `onBeforeSendHeaders` and `onSendHeaders`). I'm digging into it.

**Comment by paulgb** [comment]
Source of the above documentation: https://developer.chrome.com/extensions/webRequest

**Comment by paulgb** [comment]
Good news: I have a fix for Chrome! Just confirming that it doesn't break anything else (i.e. web or firefox); should have it out shortly.

**Comment by paulgb** [comment]
The updated extension (v4.0) is staged for review in the Chrome app store.

**Comment by pkolachi** [comment]
Thanks Paul. Tested the updated extension on Chrome and can confirm it works!

**Comment by theresia** [comment]
Thanks Paul!
