### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by homoSapiensSapiens** [paulgb/Treeverse#7]
Any tweet is adjusted LTR, even if the content is is hebrew or arabic and should show as RTL.
In case of mixed content the whole tweet gets out of order (for example, [this tweet](https://twitter.com/elongilad/status/774581918566350848) is adjusted fine in Twitter, but not in treeverse version).

**Comment by paulgb** [comment]
Thanks, I'll look into this.

**Comment by paulgb** [comment]
This will work in #7.
