### ISSUE TITLE
Use depth-first search

### ISSUE THREAD

**Issue by vcarl** [paulgb/treeverse#70]
I've noticed that a lot of threads have a number of interesting conversations tucked below the first handful of replies. The way Treeverse expands, however, expands all top-level conversations first — with a large number of 2-3 depth threads and a small number of 10+ depth threads, this takes a long time to populate the threads that I'm most interested in reading.

Come to think of it, this would also mean that I can read the first conversation uncovered as it's expanding the rest. Given that it's a relatively slow process that seems like a huge UX win

**Comment by paulgb** [comment]
Good suggestion. My involvement in Treeverse lately has mostly been just necessary maintenance but I'll keep this open in case that changes.
