### ISSUE TITLE
One branch of a thread not expanding correctly in Firefox extension

### ISSUE THREAD

**Issue by graememcc** [paulgb/treeverse#93]
Firefox 102.0
Treeverse extension 3.5

When viewing the conversation stemming from

https://twitter.com/fasterthanlime/status/1551877061878304768

and clicking "Expand All", as it traverses the conversation, the node representing tweet

https://twitter.com/fasterthanlime/status/1551878874027499521

initially shows the ellipses indicator, but when that node is visited by the expanding logic, the ellipses disappear, and no expansion of that thread takes place. There are further replies in that chain, starting from

https://twitter.com/mountain_ghosts/status/1551879395991855104

**Comment by Joshument** [comment]
Also happening to me too - looks like it has a problem when it's a bunch of linear tweets for me
