### ISSUE TITLE
Extension broken

### ISSUE THREAD

**Issue by selurvedu** [paulgb/treeverse#98]
`> GET https://api.twitter.com/2/timeline/conversation/<tweet_id>.json?include_reply_count=1&tweet_mode=extended`

`< HTTP/2 429 Too Many Requests`
```json
{"errors":[{"message":"Rate limit exceeded","code":88}]}
```

**Comment by paulgb** [comment]
Ah, I was wondering how long it would keep going after Twitter shut down their API. Thanks for reporting. Looks like this is the end of Treeverse, unless Twitter opens the API up again.

**Comment by selurvedu** [comment]
I thought so. Thanks for creating this extension, and I hope we'll see it working again some day. Of course, if Twitter wouldn't perish by then. :)

**Comment by BangyStudios** [comment]
I don't see why this extension needs to use the Twitter API when it can just scrape the page in the browser.

Gonna fork and see what I can do.

**Comment by paulgb** [comment]
It has never used the official API; it used to scrape the page HTML and then moved to reverse-engineering the internal API. My theory is that when the official API got shut down, everybody turned to reverse-engineering the internal API, so the company started cracking down on that and made it basically impossible to do.
