### ISSUE TITLE
For anyone interested, I am working on something related https://github.com/distbit0/twitterConvoToHTML

### ISSUE THREAD

**Issue by distbit0** [paulgb/treeverse#99]
https://github.com/distbit0/twitterConvoToHTML

It is a script that you can run which creates a web page containing the conversation under the tweet that you have copied to your clipboard.

i.e. it reads from your clipboard, downloads the conversation then opens it in your browser.

**Comment by arminsmith** [comment]
404 error

**Comment by distbit0** [comment]
Yeah it was impacted by twitter's api changes so I do not think it works anymore either, although perhaps twitter's api has recovered some of its functionality to the extent that my script can be exhumed...

Anyway. The source code is attached to this comment in case you are interested.
[twitterConvo.zip](https://github.com/paulgb/Treeverse/files/14006713/twitterConvo.zip)

**Comment by distbit0** [comment]
The most important missing/broken function from twitter's api last time I tried to run the script was either the function which gets replies of a tweet or which gets the parent tweet for a given tweet (I forget which one specifically was the issue, tbh).

**Comment by distbit0** [comment]
You may want to look at some of the below to find ways to recover twitter api functionality:

https://github.com/trevorhobenshield/twitter-api-client
https://github.com/Rishikant181/Rettiwt-API
https://github.com/zedeus/nitter/blob/master/src/api.nim


Let me know if you have any success! thx
